window.PUBLICATIONS = [
  {
    id: 'dengue-genomic-epi-colombia',
    title: 'Genomic epidemiology of dengue virus 2 and 3 reveals repeated introductions and exportations of several lineages in Colombia',
    citation: 'Rivero, R., Tique-Salleg, V., Echeverri-De la Hoz, D., et al. Cell Reports, 2026.',
    year: '2026',
    venue: 'Cell Reports',
    role: 'First author; lead contact',
    summary: 'Genomic analysis of more than 11,000 dengue virus genomes showing Colombia as a continental transmission hub for DENV-2 and DENV-3 movement across the Americas.',
    tags: ['Dengue', 'Genomic epidemiology', 'Phylogeography', 'Antigenic evolution'],
    pdf: 'research-pdfs/PIIS221112472501616X.pdf',
    doi: 'https://doi.org/10.1016/j.celrep.2025.116844',
    highlight: true,
    defaultShow: true
  },
  {
    id: 'snv-northwestern-united-states',
    title: 'First Sin Nombre virus (Orthohantavirus sinnombreense) genome sequences from the Northwestern United States',
    citation: 'Rickard, G., Rivero, R., Grady, A. C., et al. bioRxiv, 2025.',
    year: '2025',
    venue: 'bioRxiv',
    role: 'Co-first author',
    summary: 'Reports the first Sin Nombre virus genome sequences from the Northwestern United States and the first sequences recovered from voles, with evidence of viral reassortment.',
    tags: ['Sin Nombre virus', 'Hantavirus', 'Genomic surveillance', 'Northwestern US'],
    pdf: 'research-pdfs/2025.09.10.675434v1.full.pdf',
    doi: 'https://doi.org/10.1101/2025.09.10.675434',
    highlight: true
  },
  {
    id: 'sars-cov-2-genomic-epi-colombia',
    title: 'Genomic epidemiology of SARS-CoV-2 variants during the first two years of the pandemic in Colombia',
    citation: 'Jimenez-Silva, C., Rivero, R., Douglas, J., et al. Communications Medicine, 2023.',
    year: '2023',
    venue: 'Communications Medicine',
    role: 'Co-first author',
    summary: 'Country-scale analysis of 14,049 SARS-CoV-2 genomes describing variant introductions, replacement dynamics, and the national trajectory of the Mu variant.',
    tags: ['SARS-CoV-2', 'Genomic surveillance', 'Phylodynamics', 'Colombia'],
    pdf: 'research-pdfs/s43856-023-00328-3.pdf',
    doi: 'https://doi.org/10.1038/s43856-023-00328-3',
    overview: 'Papers/GenomicEpi.html',
    highlight: true
  },
  {
    id: 'human-dog-transmission',
    title: 'Human-to-dog transmission of SARS-CoV-2, Colombia',
    citation: 'Rivero, R., Garay, E., Botero, Y., et al. Scientific Reports, 2022.',
    year: '2022',
    venue: 'Scientific Reports',
    role: 'First author',
    summary: 'Genomic, epidemiological, and structural evidence for a symptomatic human-to-dog SARS-CoV-2 transmission event in Latin America.',
    tags: ['One Health', 'SARS-CoV-2', 'Transmission', 'Viral genomics'],
    pdf: 'research-pdfs/s41598-022-11847-9.pdf',
    doi: 'https://doi.org/10.1038/s41598-022-11847-9',
    overview: 'Papers/HumanDogTransmission.html'
  },
  {
    id: 'zika-bat-cell-lines',
    title: 'Comparative susceptibility of Old World and New World bat cell lines to Zika virus: Insights into viral replication and inflammatory responses',
    citation: 'Brown, A. J., Fagre, A. C., Gilson, J., et al. PLOS Neglected Tropical Diseases, 2025.',
    year: '2025',
    venue: 'PLOS Neglected Tropical Diseases',
    role: 'Co-author',
    summary: 'Compares Zika virus replication and inflammatory responses across bat cell lines to evaluate host susceptibility patterns.',
    tags: ['Zika virus', 'Bats', 'Host susceptibility', 'Cell culture'],
    pdf: 'research-pdfs/journal.pntd.0014065.pdf',
    doi: 'https://doi.org/10.1371/journal.pntd.0014065'
  },
  {
    id: 'influenza-h18n12-bats',
    title: 'Genomics of novel influenza A virus (H18N12) in bats, Caribe Colombia',
    citation: 'Echeverri-De la Hoz, D., Martinez-Bravo, C., Gastelbondo-Pastrana, B., et al. Scientific Reports, 2025.',
    year: '2025',
    venue: 'Scientific Reports',
    role: 'Co-author',
    summary: 'Characterizes a novel bat-associated influenza A virus genome from the Colombian Caribbean and evaluates its phylogenetic and antigenic divergence.',
    tags: ['Influenza A virus', 'Bats', 'Viral genomics', 'Colombia'],
    pdf: 'research-pdfs/s41598-025-91026-8.pdf',
    doi: 'https://doi.org/10.1038/s41598-025-91026-8'
  },
  {
    id: 'rna-extraction-kit',
    title: 'Phenol-free in-house kit for RNA extraction with applicability to SARS-CoV-2 genomic sequencing studies',
    citation: 'Gastelbondo-Pastrana, B., Florez, L., Guzman, C., et al. Journal of Virological Methods, 2025.',
    year: '2025',
    venue: 'Journal of Virological Methods',
    role: 'Co-author',
    summary: 'Describes a phenol-free RNA extraction kit designed for SARS-CoV-2 genomic sequencing workflows and local biotechnology capacity.',
    tags: ['RNA extraction', 'SARS-CoV-2', 'Sequencing', 'Biotechnology'],
    pdf: 'research-pdfs/1-s2.0-S0166093425000096-main.pdf',
    doi: 'https://doi.org/10.1016/j.jviromet.2025.115116'
  },
  {
    id: 'rbd-trimeric-vaccine',
    title: 'Preclinical evaluation of the RBD-Trimeric vaccine: A novel approach to strengthening biotechnological sovereignty in developing countries against SARS-CoV-2 variants',
    citation: 'Florez, L., Echeverri-De la Hoz, D., Calderon, A., et al. Travel Medicine and Infectious Disease, 2025.',
    year: '2025',
    venue: 'Travel Medicine and Infectious Disease',
    role: 'Co-author',
    summary: 'Preclinical evaluation of an RBD-trimer immunogen designed in silico from SARS-CoV-2 variant information.',
    tags: ['SARS-CoV-2', 'Vaccine', 'RBD trimer', 'Preclinical study'],
    pdf: 'research-pdfs/1-s2.0-S1477893925000262-main.pdf',
    doi: 'https://doi.org/10.1016/j.tmaid.2025.102820'
  },
  {
    id: 'arha-database-protocol',
    title: 'Protocol to produce a systematic Arenavirus and Hantavirus host-pathogen database: Project ArHa',
    citation: 'Simons, D., Rivero, R., Martinez-Checa Guiote, A., et al. Wellcome Open Research, 2025.',
    year: '2025',
    venue: 'Wellcome Open Research',
    role: 'Co-author',
    summary: 'Study protocol for a systematic host-pathogen database focused on arenaviruses, hantaviruses, and zoonotic spillover context.',
    tags: ['Arenavirus', 'Hantavirus', 'Host-pathogen database', 'Zoonoses'],
    pdf: 'research-pdfs/804dd92a-effe-4cbc-ba52-b87837e1c049_24037_-_david_simons_v2.pdf',
    doi: 'https://doi.org/10.12688/wellcomeopenres.24037.2'
  },
  {
    id: 'jngmen-tick-virus-colombia',
    title: 'Hard ticks in the Colombian Caribbean harbor the Jingmen tick virus: an emerging arbovirus of public health concern',
    citation: 'Lopez, Y., Thomas, R., Munoz-Leal, S., et al. Parasites & Vectors, 2024.',
    year: '2024',
    venue: 'Parasites & Vectors',
    role: 'Co-author',
    summary: 'Reports Jingmen tick virus detection in hard ticks from the Colombian Caribbean using next-generation sequencing.',
    tags: ['Jingmen tick virus', 'Ticks', 'Arbovirus', 'Metagenomics'],
    pdf: 'research-pdfs/s13071-024-06362-x.pdf',
    doi: 'https://doi.org/10.1186/s13071-024-06362-x'
  },
  {
    id: 'first-rdrp-summit',
    title: 'Consensus statement from the first RdRp Summit: advancing RNA virus discovery at scale across communities',
    citation: 'Charon, J., Olendraite, I., Forgia, M., et al. Frontiers in Virology, 2024.',
    year: '2024',
    venue: 'Frontiers in Virology',
    role: 'Contributor',
    summary: 'Community consensus statement on RNA virus discovery, RdRp-centered detection, genome annotation, and metadata standards.',
    tags: ['RNA viruses', 'Virus discovery', 'RdRp', 'Metagenomics'],
    pdf: 'research-pdfs/fviro-04-1371958.pdf',
    doi: 'https://doi.org/10.3389/fviro.2024.1371958'
  },
  {
    id: 'second-rdrp-summit',
    title: 'Consensus statement from the second RdRp Summit: towards a unified framework for RNA virus biology',
    citation: 'Lucaci, A. G., Shaikh, H. M., Chong, L. C., et al. 2025.',
    year: '2025',
    venue: 'Consensus statement',
    role: 'Contributor',
    summary: 'Community statement outlining a shared framework for RNA virus biology across discovery, annotation, evolution, and ecology.',
    tags: ['RNA viruses', 'RdRp', 'Virus biology', 'Community standards'],
    pdf: 'research-pdfs/CONSENSUS_RdRpSummit2025.pdf'
  },
  {
    id: 'arbovirus-genomic-surveillance-comment',
    title: 'Arbovirus researchers unite: expanding genomic surveillance for an urgent global need',
    citation: 'The Lancet Global Health, 2023.',
    year: '2023',
    venue: 'The Lancet Global Health',
    role: 'Consortium contributor',
    summary: 'Commentary calling for routine and sustainable genomic surveillance for high-impact arboviruses.',
    tags: ['Arboviruses', 'Genomic surveillance', 'Dengue', 'Global health'],
    pdf: 'research-pdfs/PIIS2214109X2300325X.pdf',
    doi: 'https://doi.org/10.1016/S2214-109X(23)00325-X'
  },
  {
    id: 'borrelia-opossums-colombia',
    title: 'Borrelia puertoricensis in opossums (Didelphis marsupialis) from Colombia',
    citation: 'Lopez, Y., Faccini-Martinez, A. A., Munoz-Leal, S., et al. Parasites & Vectors, 2023.',
    year: '2023',
    venue: 'Parasites & Vectors',
    role: 'Co-author',
    summary: 'Reports Borrelia puertoricensis detection in opossums from Colombia, expanding knowledge of tick-borne spirochete ecology.',
    tags: ['Borrelia', 'Opossums', 'Tick-borne disease', 'Colombia'],
    pdf: 'research-pdfs/s13071-023-06016-4.pdf',
    doi: 'https://doi.org/10.1186/s13071-023-06016-4'
  },
  {
    id: 'covid-presymptomatic-tropical-colombia',
    title: 'SARS-CoV-2 in a tropical area of Colombia: a remarkable conversion of presymptomatic to symptomatic people impacts public health',
    citation: 'Martinez, C., Serrano-Coll, H., Faccini, A., et al. BMC Infectious Diseases, 2022.',
    year: '2022',
    venue: 'BMC Infectious Diseases',
    role: 'Co-author',
    summary: 'Epidemiological study of SARS-CoV-2 clinical dynamics in tropical Colombia, with emphasis on presymptomatic-to-symptomatic conversion.',
    tags: ['SARS-CoV-2', 'Epidemiology', 'Public health', 'Colombia'],
    pdf: 'research-pdfs/s12879-022-07575-0.pdf',
    doi: 'https://doi.org/10.1186/s12879-022-07575-0'
  },
  {
    id: 'rbd-vaccine-murine-model',
    title: 'Immunogenicity and safety of a RBD vaccine against SARS-CoV-2 in a murine model',
    citation: 'Diaz, A., Serrano-Coll, H., Botero, Y., et al. Travel Medicine and Infectious Disease, 2022.',
    year: '2022',
    venue: 'Travel Medicine and Infectious Disease',
    role: 'Co-author',
    summary: 'Preclinical murine model study evaluating immunogenicity and safety of a SARS-CoV-2 RBD vaccine candidate.',
    tags: ['SARS-CoV-2', 'Vaccine', 'RBD', 'Murine model'],
    pdf: 'research-pdfs/1-s2.0-S1477893922001739-main.pdf',
    doi: 'https://doi.org/10.1016/j.tmaid.2022.102427'
  },
  {
    id: 'coronavac-amazon-colombia',
    title: 'Effectiveness of the CoronaVac vaccine in a region of the Colombian Amazon: was herd immunity achieved?',
    citation: 'Serrano-Coll, H., Miller, H., Guzman, C., et al. Tropical Diseases, Travel Medicine and Vaccines, 2022.',
    year: '2022',
    venue: 'Tropical Diseases, Travel Medicine and Vaccines',
    role: 'Co-author',
    summary: 'Evaluates CoronaVac effectiveness in an Amazonian population near a region of SARS-CoV-2 variant circulation.',
    tags: ['CoronaVac', 'COVID-19', 'Amazon', 'Vaccination'],
    pdf: 'research-pdfs/s40794-021-00159-x.pdf',
    doi: 'https://doi.org/10.1186/s40794-021-00159-x'
  },
  {
    id: 'sars-cov-2-colombian-tropics',
    title: 'SARS-CoV-2 in eight municipalities of the Colombian tropics: high immunity, clinical and sociodemographic outcomes',
    citation: 'Garay, E., Serrano-Coll, H., Rivero, R., et al. Transactions of the Royal Society of Tropical Medicine and Hygiene, 2022.',
    year: '2022',
    venue: 'Transactions of the Royal Society of Tropical Medicine and Hygiene',
    role: 'Co-author',
    summary: 'Serological study estimating SARS-CoV-2 immunity and clinical/sociodemographic associations across municipalities in Cordoba, Colombia.',
    tags: ['SARS-CoV-2', 'Seroprevalence', 'Colombian tropics', 'Public health'],
    pdf: 'research-pdfs/trab094.pdf',
    doi: 'https://doi.org/10.1093/trstmh/trab094'
  },
  {
    id: 'amazon-indigenous-sars-cov-2',
    title: 'High prevalence of SARS-CoV-2 in an Indigenous community of the Colombian Amazon region',
    citation: 'Serrano-Coll, H., Miller, H., Rodriguez-Van Der Hamen, C., et al. Tropical Medicine and Infectious Disease, 2021.',
    year: '2021',
    venue: 'Tropical Medicine and Infectious Disease',
    role: 'Co-author',
    summary: 'Describes SARS-CoV-2 seropositivity, spatial distribution, and clinical factors in an Indigenous community in the Colombian Amazon.',
    tags: ['SARS-CoV-2', 'Serology', 'Indigenous health', 'Amazon'],
    pdf: 'research-pdfs/tropicalmed-06-00191.pdf',
    doi: 'https://doi.org/10.3390/tropicalmed6040191'
  },
  {
    id: 'sars-cov-2-reinfection-colombia',
    title: 'A first probable case of SARS-CoV-2 reinfection in Colombia',
    citation: 'Novoa, W., Miller, H., Mattar, S., et al. Annals of Clinical Microbiology and Antimicrobials, 2021.',
    year: '2021',
    venue: 'Annals of Clinical Microbiology and Antimicrobials',
    role: 'Co-author',
    summary: 'Letter describing an early probable case of SARS-CoV-2 reinfection in Colombia.',
    tags: ['SARS-CoV-2', 'Reinfection', 'Clinical microbiology', 'Colombia'],
    pdf: 'research-pdfs/s12941-020-00413-8.pdf',
    doi: 'https://doi.org/10.1186/s12941-020-00413-8'
  },
  {
    id: 'serology-cross-reactivity',
    title: 'Serological cross-reactivity using a SARS-CoV-2 ELISA test in acute Zika virus infection, Colombia',
    citation: 'Faccini-Martinez, A. A., Rivero, R., Garay, E., et al. International Journal of Infectious Diseases, 2020.',
    year: '2020',
    venue: 'International Journal of Infectious Diseases',
    role: 'Co-author',
    summary: 'Evaluates SARS-CoV-2 ELISA cross-reactivity in samples from Zika, dengue, and chikungunya cohorts in an arbovirus-endemic setting.',
    tags: ['Serology', 'Zika virus', 'SARS-CoV-2', 'Diagnostics'],
    pdf: 'research-pdfs/1-s2.0-S1201971220321676-main.pdf',
    doi: 'https://doi.org/10.1016/j.ijid.2020.09.1451',
    overview: 'Papers/SerologicalCrossReact.html'
  },
  {
    id: 'sars-cov-2-caribbean-seroprevalence',
    title: 'Severe acute respiratory syndrome coronavirus 2 seroprevalence among adults in a tropical city of the Caribbean area, Colombia',
    citation: 'Open Forum Infectious Diseases, 2020.',
    year: '2020',
    venue: 'Open Forum Infectious Diseases',
    role: 'Co-author',
    summary: 'Seroprevalence study estimating SARS-CoV-2 exposure among adults in a tropical Colombian Caribbean city.',
    tags: ['SARS-CoV-2', 'Seroprevalence', 'Caribbean Colombia', 'Herd immunity'],
    pdf: 'research-pdfs/ofaa550.pdf',
    doi: 'https://doi.org/10.1093/ofid/ofaa550'
  },
  {
    id: 'sars-cov-2-cohort-caribbean',
    title: 'Epidemiological and viral features of a cohort of SARS-CoV-2 symptomatic and asymptomatic individuals in an area of the Colombian Caribbean',
    citation: 'Mattar, S., et al. Annals of Clinical Microbiology and Antimicrobials, 2020.',
    year: '2020',
    venue: 'Annals of Clinical Microbiology and Antimicrobials',
    role: 'Co-author',
    summary: 'Cohort study describing epidemiological and viral features of symptomatic and asymptomatic SARS-CoV-2 infections in the Colombian Caribbean.',
    tags: ['SARS-CoV-2', 'Asymptomatic infection', 'Epidemiology', 'Colombia'],
    pdf: 'research-pdfs/s12941-020-00397-5.pdf',
    doi: 'https://doi.org/10.1186/s12941-020-00397-5'
  },
  {
    id: 'equine-encephalitis-climate-colombia',
    title: 'Climatic variables and the reemerging Eastern and Venezuelan equine encephalitis in equines, Colombia 2005-2023',
    citation: 'Mattar, S., Paternina, D., Herazo, R., et al. SSRN preprint, 2023.',
    year: '2023',
    venue: 'SSRN preprint',
    role: 'Co-author',
    summary: 'Preprint analyzing climatic variables and the reemergence of Eastern and Venezuelan equine encephalitis in Colombia.',
    tags: ['Equine encephalitis', 'Climate', 'Vector-borne disease', 'Colombia'],
    pdf: 'research-pdfs/ssrn-4590913.pdf'
  }
];
